In [1]:
import pandas as pd

In [22]:
# Basic conversion
'2023-09-30'
print(pd.to_datetime('2023-09-30'))
pd.to_datetime('2023-09-30')

2023-09-30 00:00:00

Timestamp('2023-09-30 00:00:00')

In [23]:
# Works with common formats
print(pd.to_datetime('09/30/2023'))

2023-09-30 00:00:00

In [24]:
# Natural language dates
print(pd.to_datetime('September 30, 2023'))

2023-09-30 00:00:00

In [25]:
# With format specification
pd.to_datetime('09/30/2023', format='%m/%d/%Y')
print(pd.to_datetime('09/30/2023', format='%m/%d/%Y'))
pd.to_datetime('Saturday, September 30, 2023', format='%A, %B %d, %Y')

2023-09-30 00:00:00

Timestamp('2023-09-30 00:00:00')

In [26]:
# From year, month, day components
pd.Timestamp(year=2023, month=9, day=30, hour=14, minute=35)

Timestamp('2023-09-30 14:35:00')

In [27]:
# From a dictionary (scalar or Series)
pd.to_datetime({
   'year': [2023, 2023],
   'month': [9, 10],
   'day': [30, 15],
   'hour': [14, 8]
})

0   2023-09-30 14:00:00
1   2023-10-15 08:00:00
dtype: datetime64[us]

In [29]:
pd.to_datetime('Saturday, September 30, 2023', format='%A, %B %d, %Y')

Timestamp('2023-09-30 00:00:00')

The output is the same because, while you provided different input formats for Pandas to interpret, the resulting data type in memory is identical.

Pandas does not "remember" the format you used to create the date; it only cares about the absolute point in time that the date represents. Once Pandas successfully parses your input, it standardizes the result into a datetime64 object, which is always displayed using a standard ISO-like format: ```YYYY-MM-DD HH:MM:SS```.

**Why this happens**

- **Parsing vs. Storing:** The format argument is a "map" that tells Pandas how to navigate your input string to find the year, month, and day. Once it finds those components, it discards the original string and stores the date internally as a numeric timestamp (the number of nanoseconds since January 1, 1970).

- **Standardized Display:** When you print() or display a datetime object in Jupyter, Pandas uses a default representation. It doesn't matter if you typed the date as "September 30th" or "09/30/23"—internally, they are the exact same point in time, so they are printed the same way.

**How to see them differently**

If you want to "see" your dates in different formats, you are no longer talking about the datetime64 object itself, but rather a string representation of that date. To achieve this, you use the ```.strftime()``` method.

Think of the input format as the language the data is written in, and the datetime object as the universal meaning behind those words. Pandas translates all those different languages into one universal, high-performance internal format so that it can perform calculations, sorting, and grouping on them efficiently.

In [30]:
date_obj = pd.to_datetime('09/30/2023', format='%m/%d/%Y')

# You can convert that object into any string format you want:
print(date_obj.strftime('%d-%m-%Y')) # Output: 30-09-2023
print(date_obj.strftime('%B %d, %Y')) # Output: September 30, 2023

30-09-2023
September 30, 2023

In [32]:
# From Unix timestamp (seconds since Jan 1, 1970)
# Unit can be 's', 'ms', 'us', 'ns'    
pd.to_datetime(1664582400, unit='s')

Timestamp('2022-10-01 00:00:00')

In [38]:
# Sample dates
date_series = pd.to_datetime(['2023-09-30', '2023-10-15', '2023-12-31'])
date_series

DatetimeIndex(['2023-09-30', '2023-10-15', '2023-12-31'], dtype='datetime64[us]', freq=None)

### Why Pandas makes it an Index?
Pandas defaults to creating an Index when you use *pd.to_datetime()* on a list because indexes are designed to be the "labels" of a DataFrame. By giving you a DatetimeIndex, Pandas immediately allows you to do things like index-based alignment and time-series slicing (like ```df.loc['2023-10'])``` without any extra work.

In [20]:
# Access the raw values as a NumPy array
print(date_series.values)

# Convert to a standard Python list
print(date_series.tolist())

# Access a specific value by position
print(date_series[0])

['2023-09-30T00:00:00.000000' '2023-10-15T00:00:00.000000'
 '2023-12-31T00:00:00.000000']
[Timestamp('2023-09-30 00:00:00'), Timestamp('2023-10-15 00:00:00'), Timestamp('2023-12-31 00:00:00')]
2023-09-30 00:00:00

In [39]:
# Create a sample DataFrame to demonstrate
df = pd.DataFrame({'Data': [10, 20, 30]}, index=date_series)
df

            Data
2023-09-30    10
2023-10-15    20
2023-12-31    30

In [41]:
# Slice by month or year 
print(df.loc['2023-10'])  # Returns everything in October 2023. 
# print(df['2023-10']) # it throws an error
print(df['2023-09-30':'2023-11-01']) # Returns everything in this range

            Data
2023-10-15    20
            Data
2023-09-30    10
2023-10-15    20

In [46]:
# Shuffle the entire DataFrame
df_shuffled = df.sample(frac=1)
df_shuffled

            Data
2023-10-15    20
2023-09-30    10
2023-12-31    30

In [47]:
# Slice by month or year 
print(df_shuffled.loc['2023-10'])  # Returns everything in October 2023. 
print(df_shuffled['2023-09-30':'2023-11-01']) # Returns everything in this range. It trows an error because it is not sorted

            Data
2023-10-15    20

KeyError: 'Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is not allowed.'

In [49]:
df_shuffled.sort_index(inplace=True)
df_shuffled

            Data
2023-09-30    10
2023-10-15    20
2023-12-31    30

In [50]:
print(df_shuffled['2023-09-30':'2023-11-01'])

            Data
2023-09-30    10
2023-10-15    20

In [14]:
# Basic date components
# [2023, 2023, 2023]  - Extract the year as integers
date_series.year

Index([2023, 2023, 2023], dtype='int32')

In [ ]:
# [9, 10, 12]         - Month as integers (1-12)        
date_series.month

In [ ]:
# [30, 15, 31]        - Day of month as integers (1-31)
date_series.day

In [ ]:
# Week-related components
# [5, 6, 6]           - Day of week as integers (0=Monday, 6=Sunday)
date_series.dayofweek

In [ ]:
# ['Saturday', 'Sunday', 'Monday'] - Day name as strings
date_series.day_name()

In [ ]:
# DataFrame with year, week, and day columns (ISO calendar)
date_series.isocalendar()

In [ ]:
# [39, 41, 52]        - ISO week number (1-53)
date_series.isocalendar().week

### Working with Periods
A Period is fundamentally different from a Timestamp:

- **Timestamp:** Represents a single, specific point in time (e.g., "2023-01-01 09:00:00").

- **Period:** Represents a fixed span of time (e.g., the entire year of 2023).

**Why this is useful**

For some projects, periods are extremely powerful for downsampling and financial reporting. For example, if we have daily patrol logs but need to report budget or resource consumption by year or fiscal quarter, converting our data to Period objects allows us to group and aggregate the data cleanly:

```python
# Convert daily data to year-period
df['year'] = df['order_date'].dt.to_period('Y')

# Group by the period
annual_report = df.groupby('year')['total_price'].sum()

In [83]:
# Create Period objects
# When we execute pd.Period('2023', freq='Y'), Pandas interprets this as a single, discrete Period representing the entirety of the year 2023.
# The Output Explained: Period('2023', 'Y-DEC')
# '2023': This is the label of the period. Since we specified the frequency as 'Y' (Year), Pandas sets the period to encompass the full chronological span of that year.
#'Y-DEC': This part is the Frequency Alias.
# Y stands for Year.
# -DEC tells us the "anchor" month. By default, Pandas assumes a standard calendar year, which ends in December. If we were working with a fiscal year that ended in June, you would see 'Y-JUN'.
year_period = pd.Period('2023', freq='Y')  # Full year
year_period

Period('2023', 'Y-DEC')

In [87]:
# Changing to the US Federal Fiscal Year
# We can modify our code to anchor the period to September.
# Y: Stands for Year.
# -SEP: Tells Pandas that the period concludes at the end of September.
# The Result: When we run this, the output will be Period('2023', 'A-SEP'). This effectively treats the time span from October 1, 2022, to September 30, 2023, as the "2023 Fiscal Year."
fiscal_period = pd.Period('2023', freq='Y-SEP') 
print(fiscal_period)

# Check the start and end of that period
print(f"Start: {fiscal_period.start_time}")
print(f"End: {fiscal_period.end_time}")

2023
Start: 2022-10-01 00:00:00
End: 2023-09-30 23:59:59.999999

In [89]:
# Create Period objects
# The Breakdown
# '2023Q1': This is our Label. It represents the first three-month quarter of the year 2023 (January, February, and March).
# 'Q-DEC': This is our Frequency.
# Q: Indicates a Quarter frequency.
# -DEC: This is the anchor month. By default, Pandas anchors quarters to the end of the calendar year (December). This means the quarters are defined as:
# Q1: Jan–Mar
# Q2: Apr–Jun
# Q3: Jul–Sep
# Q4: Oct–Dec
quarter_period = pd.Period('2023Q1', freq='Q')  # First quarter
quarter_period

# Check the start and end dates of this specific quarter
print(f"Start: {quarter_period.start_time}")
print(f"End: {quarter_period.end_time}")

Start: 2023-01-01 00:00:00
End: 2023-03-31 23:59:59.999999

In [90]:
# Fiscal year
quarter_period_fy = pd.Period('2023Q1', freq='Q-SEP')  # First quarter
quarter_period_fy

# Check the start and end dates of this specific quarter
print(f"Start: {quarter_period_fy.start_time}")
print(f"End: {quarter_period_fy.end_time}")

Start: 2022-10-01 00:00:00
End: 2022-12-31 23:59:59.999999

In [91]:
# Create Period objects
month_period = pd.Period('2023-01', freq='M')   # January
month_period

# Check the start and end dates of this specific month
print(f"Start: {month_period.start_time}")
print(f"End: {month_period.end_time}")

Start: 2023-01-01 00:00:00
End: 2023-01-31 23:59:59.999999

In [95]:
# Converting datetime to period
date_series = pd.to_datetime(['2023-01-15', '2023-02-28', '2023-04-10'])
date_series
# Monthly periods: ['2023-01', '2023-02', '2023-04']
date_series.to_period('M')

PeriodIndex(['2023-01', '2023-02', '2023-04'], dtype='period[M]')

In [97]:
# Quarterly periods: ['2023Q1', '2023Q1', '2023Q2']             
date_series.to_period('Q')

PeriodIndex(['2023Q1', '2023Q1', '2023Q2'], dtype='period[Q-DEC]')

In [98]:
# Yearly periods: ['2023', '2023', '2023']              
date_series.to_period('Y')

PeriodIndex(['2023', '2023', '2023'], dtype='period[Y-DEC]')

### Handling Timezones

In [100]:
# Creating timezone-aware timestamps
# .tz_localize('US/Eastern'): This is the "attachment" step. It tells Pandas, "Take that specific moment and treat it as if it occurred in the Eastern Standard/Daylight Time zone."
pd.Timestamp('2023-09-30 14:30:00', tz='UTC')
pd.Timestamp('2023-09-30 14:30:00').tz_localize('US/Eastern')

Timestamp('2023-09-30 14:30:00-0400', tz='US/Eastern')

In [101]:
# Converting timezones
# tz_convert(): Changes a timezone-aware timestamp from one zone to another. (Use this for comparing data from different parts of the world).
# 07:30:00: Because the Pacific Timezone (in September, which is PDT) is 7 hours behind UTC, Pandas subtracts 7 hours from 14:30:00, resulting in 07:30:00 (7:30 AM).
# -0700: This is the "UTC Offset." It tells you that this specific moment is 7 hours behind the reference UTC time.
ts = pd.Timestamp('2023-09-30 14:30:00', tz='UTC')
ts.tz_convert('US/Pacific')  # Converts from UTC to Pacific

Timestamp('2023-09-30 07:30:00-0700', tz='US/Pacific')

In [104]:
# Create a Series of 5 naive timestamps
data = {
    'timestamp': pd.to_datetime([
        '2026-06-25 08:00:00',
        '2026-06-25 09:30:00',
        '2026-06-25 12:00:00',
        '2026-06-25 15:45:00',
        '2026-06-25 20:00:00'
    ])
}
df = pd.DataFrame(data)
df

            timestamp
0 2026-06-25 08:00:00
1 2026-06-25 09:30:00
2 2026-06-25 12:00:00
3 2026-06-25 15:45:00
4 2026-06-25 20:00:00

In [105]:
# Converting a series of timestamps to different timezone
df['timestamp_utc'] = df['timestamp'].dt.tz_localize('UTC')
df['timestamp_utc']

0   2026-06-25 08:00:00+00:00
1   2026-06-25 09:30:00+00:00
2   2026-06-25 12:00:00+00:00
3   2026-06-25 15:45:00+00:00
4   2026-06-25 20:00:00+00:00
Name: timestamp_utc, dtype: datetime64[us, UTC]

In [106]:
df['timestamp_local'] = df['timestamp_utc'].dt.tz_convert('US/Eastern')
df['timestamp_local']

0   2026-06-25 04:00:00-04:00
1   2026-06-25 05:30:00-04:00
2   2026-06-25 08:00:00-04:00
3   2026-06-25 11:45:00-04:00
4   2026-06-25 16:00:00-04:00
Name: timestamp_local, dtype: datetime64[us, US/Eastern]

In [107]:
# Removing timezone information
df['timestamp_naive'] = df['timestamp_utc'].dt.tz_localize(None)
df['timestamp_naive']

0   2026-06-25 08:00:00
1   2026-06-25 09:30:00
2   2026-06-25 12:00:00
3   2026-06-25 15:45:00
4   2026-06-25 20:00:00
Name: timestamp_naive, dtype: datetime64[us]

# Difference between pandas.Timestamp and datetime64[us]
The confusion between pandas.Timestamp and datetime64[us] is common, as they both represent a specific point in time. The difference lies in whether you are looking at the object itself or the data type stored in a column.

**1.  pandas.Timestamp (The Object)**
Think of Timestamp as the individual unit of time. It is a single object that acts like a Python datetime object but with extra "superpowers" specifically for data science.

- **Usage:** You use it to represent one single moment in your code.

- **Capabilities:** Because it is a "Pandas" object, it has built-in methods for time-zone awareness, frequency handling, and arithmetic (e.g., ts + pd.Timedelta(days=1)).

In [7]:
# Example: Creating a single Timestamp object
ts = pd.Timestamp('2026-06-24 20:32:00')
print(type(ts)) # <class 'pandas.Timestamp'>

<class 'pandas.Timestamp'>

**2. datetime64[us] (The Data Type)**
datetime64[us] is the memory representation (dtype) used by Pandas when it stores a column of dates.

- **Usage:** You see this when you inspect df.info() or df.dtypes. It describes how the data is packed into your computer's RAM.

- **The [us] part:** This specifically denotes microsecond precision. Other common types are datetime64[ns] (nanoseconds), which is the default for most modern Pandas operations.

- **Efficiency:** This is a NumPy-based type. It is optimized for performance, allowing Pandas to store millions of dates in a contiguous block of memory, which is much faster than storing millions of individual Timestamp objects.

In [53]:
# Load the data
df = pd.read_csv('students_updated.csv')

In [54]:
# Convert EnrollmentDate to datetime
# 'coerce' turns invalid/missing dates into NaT (Not a Time)
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'], errors='coerce')

In [55]:
# Verify the conversion
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            20 non-null     str
 1   Age             19 non-null     float64
 2   Grade           19 non-null     float64
 3   City            19 non-null     str
 4   EnrollmentDate  10 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(2), str(2)
memory usage: 932.0 bytes
None

In [56]:
# 3. Extract the year
# df['Enrollment_Year'] = df['EnrollmentDate'].year # It throws an error. Since it is a Series, we need to use the dt accessor
df['Enrollment_Year'] = df['EnrollmentDate'].dt.year

In [76]:
# Display the results
df[['Name', 'EnrollmentDate', 'Enrollment_Year']].tail()

      Name             EnrollmentDate  Enrollment_Year
15   Kevin 2026-06-13 14:48:35.126933           2026.0
16    Liam 2026-06-12 14:48:35.126935           2026.0
17     Mia 2026-06-11 14:48:35.126936           2026.0
18    Noah 2026-06-10 14:48:35.126938           2026.0
19  Olivia 2026-06-09 14:48:35.126939           2026.0

In [66]:
df['EnrollmentDate'].dt.month
df['EnrollmentDate'].dt.day
df['EnrollmentDate'].dt.hour
df['EnrollmentDate'].dt.minute
df['EnrollmentDate'].dt.second
df['EnrollmentDate'].dt.quarter
df['EnrollmentDate'].dt.dayofweek
df['EnrollmentDate'].dt.day_name() 
df['EnrollmentDate'].dt.isocalendar()
df['EnrollmentDate'].dt.isocalendar().week 
df['EnrollmentDate'].dt.isocalendar().year

0     <NA>
1     <NA>
2     <NA>
3     <NA>
4     <NA>
5     <NA>
6     <NA>
7     <NA>
8     <NA>
9     <NA>
10    2026
11    2026
12    2026
13    2026
14    2026
15    2026
16    2026
17    2026
18    2026
19    2026
Name: year, dtype: UInt32

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10    35.0
11    35.0
12    35.0
13    35.0
14    35.0
15    35.0
16    35.0
17    35.0
18    35.0
19    35.0
Name: EnrollmentDate, dtype: float64